
-- MySQL --
CREATE TABLE MyUsers (
    user_id     INT(10) NOT NULL,
    user_name   VARCHAR(150),
    SALARY      VARCHAR(100)
);


-- Oracle --
CREATE TABLE MyUsers (
    user_id NUMBER(10) NOT NULL,
    user_name VARCHAR2(150),
    SALARY VARCHAR2(100),
    CONSTRAINT MyUsers_pk PRIMARY KEY (user_id)
);

-- sample data --
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('1', 'user1', '100');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('2', 'user2', '200');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('3', 'user3', '300');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('4', 'user4', '400');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('5', 'user5', '500');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('6', 'user6', '600');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('7', 'user7', '700');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('8', 'user8', '800');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('9', 'user9', '900');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('10', 'user10', '1000');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('11', 'user11', '1100');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('12', 'user12', '1200');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('13', 'user13', '1300');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('14', 'user14', '1400');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('15', 'user15', '1500');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('16', 'user16', '1600');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('17', 'user17', '1700');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('18', 'user18', '1800');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('19', 'user19', '1900');
INSERT INTO MYUSERS (USER_ID, USER_NAME, SALARY) VALUES ('20', 'user20', '2000');
commit;
